### ISSUE TITLE
Always show the back button

### ISSUE THREAD

**Issue by amineharbaoui** [TutorialsAndroid/FilePicker#4] opened 2019-10-17 10:09 UTC
Why we can't go back on the chosen directory ? the back button only appear if I enter to the directory 

![Screenshot_20191017_120235_ubudu com mapscouter](https://user-images.githubusercontent.com/10993559/66999538-7e0d9e00-f0d6-11e9-9fde-c2ad584c2de4.jpg)

This is the default directory without the back button otherwise if I choose a directory I can go back 

![Screenshot_20191017_120241_ubudu com mapscouter](https://user-images.githubusercontent.com/10993559/66999667-bdd48580-f0d6-11e9-80e2-77c7df2df392.jpg)

**Comment by TutorialsAndroid** [comment] 2019-10-30 09:09
> 
> 
> Why we can't go back on the chosen directory ? the back button only appear if I enter to the directory
> 
> ![Screenshot_20191017_120235_ubudu com mapscouter](https://user-images.githubusercontent.com/10993559/66999538-7e0d9e00-f0d6-11e9-9fde-c2ad584c2de4.jpg)
> 
> This is the default directory without the back button otherwise if I choose a directory I can go back
> 
> ![Screenshot_20191017_120241_ubudu com mapscouter](https://user-images.githubusercontent.com/10993559/66999667-bdd48580-f0d6-11e9-80e2-77c7df2df392.jpg)

sorry for very late reply we will soon add back button to this library.

**Comment by PembaTamang** [comment] 2019-12-16 09:47
when will you do it. I am also seeing some inner folders. I cannot navigate back from there.

**Comment by TutorialsAndroid** [comment] 2019-12-17 05:05
> when will you do it. I am also seeing some inner folders. I cannot navigate back from there.

Soon I will update in one month. Sorry for very late reply. When I will get free I will update this library.

**Comment by PembaTamang** [comment] 2019-12-17 05:13
> > when will you do it. I am also seeing some inner folders. I cannot navigate back from there.
> 
> Soon I will update in one month. Sorry for very late reply. When I will get free I will update this library.

ok thank you

**Comment by sidtact** [comment] 2020-02-20 15:31
is this going to happen?

**Comment by TutorialsAndroid** [comment] 2020-02-20 17:41
> is this going to happen?

Actually I have a really busy schedule I can't go through each and each library but still I'm trying to give a perfect output to you. But still if you want back button in this library then you can contribute to this library I will add your name in Readme file for your contribution.

**Comment by kocheick** [comment] 2020-03-31 19:18
Not sure I understand well what the issue is... but @amineharbaoui @sidtact in order to go back you simply press the "..." ( 3 dots ) folder and it will bring you back to the parent folder.

**Comment by TutorialsAndroid** [comment] 2023-09-07 06:51
> Not sure I understand well what the issue is... but @amineharbaoui @sidtact in order to go back you simply press the "..." ( 3 dots ) folder and it will bring you back to the parent folder.

I have tested this library in Android 13 below versions and the back button is cleary visible. As @kocheick said you can simple press the "..." ( 3dots ) folder and it will go back to parent folder.

But still I will recommend you to update to the latest version of this library 9.1.4. I'm now closing this issue.

**Closed as completed by TutorialsAndroid** 2023-09-07 06:51 UTC
